// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1DSyncServer.Data;

namespace _1DSyncServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("_1DSync.Models.PseudoDynamicEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTimeCol1");

                    b.Property<DateTime>("DateTimeCol2");

                    b.Property<double>("DoubleCol1");

                    b.Property<double>("DoubleCol2");

                    b.Property<double>("DoubleCol3");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("StringCol1");

                    b.Property<string>("StringCol2");

                    b.Property<string>("StringCol3");

                    b.Property<string>("StringCol4");

                    b.Property<string>("StringCol5");

                    b.Property<string>("StringCol6");

                    b.Property<string>("StringCol7");

                    b.Property<string>("StringCol8");

                    b.Property<string>("StringCol9");

                    b.Property<bool>("SyncStatus");

                    b.HasKey("Id");

                    b.ToTable("PseudoDynamicEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
